### ISSUE TITLE
Script 7A Discrepancy between readme and code

### ISSUE THREAD

**Issue by pdefusco** [cloudera/CML_AMP_Churn_Prediction#6]
Hi Andrew,

I am running each step in the code folder manually as if I were a workshop attendee and I noticed in scripts 7A we use the cmlbootstrap lib to grab the latest model id (lines 200 - 217) based on model name and we assume the deployed model name is "Churn Model API Endpoint" (line 207). 

However, if we create a model following the instructions in the readme (the one in the code folder) for part "5 Serve Model" it will be called "explainer" so script 7A doesn't pick up the model correctly and fails. 

We are going to use this project on Wednesday 4/21 for a large workshop and I was wondering if you could please fix it by then if possible.

Thanks,
Paul

**Comment by andrewrreed** [comment]
Thanks for this catch @pdefusco! Please let me know if there are other items you find as you run the workshop, appreciate the feedback
